{
  "code": 200,
  "message": "操作成功!",
  "data": {
    "Version": "PS-20210825-16",
    "Generator": "2026-06-15 15:44:13",
    "Unit": null,
    "Name": "SAW 13 - OPTIMIZED EXPORT - SOURCE LENGTH - QTY EXPANDED",
    "Bars": [
      {
        "DXF_Name": "SL-LHB8004-20T",
        "BarNumber": 1,
        "MaxY": 45.0,
        "MaxZ": 83.1,
        "Length": 4800.0,
        "BarName": "G20 - 4760.05.00.4880",
        "BarColor": "/",
        "BarLeftLength": 578.8,
        "BarType": 2,
        "BarCad": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_182c74ad-02f4-4ba2-9de1-8171424f9168.png",
        "BarId": 134,
        "BarCad_file": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_22bbbd92-13c6-4baf-ab21-b5d1051b161c.dxf",
        "SortingCode": "G20",
        "Machining": {
          "Faces": []
        },
        "profile_type": null,
        "profile_type_sort": 1,
        "Piece": [
          {
            "PieceNumber": 1,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600451 A-A-S2-G20-R01-Q01",
            "Customer": "JOB 2600451",
            "Cc_code": "2600451",
            "Buyer": "2600451 A",
            "BuyAddress": "A-S2",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600451 A",
            "GroupCode": "G20",
            "Cut": {
              "Length": 670.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 2,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600451 A-A-S2-G20-R01-Q02",
            "Customer": "JOB 2600451",
            "Cc_code": "2600451",
            "Buyer": "2600451 A",
            "BuyAddress": "A-S2",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600451 A",
            "GroupCode": "G20",
            "Cut": {
              "Length": 670.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 3,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-A-S1-G20-R02-Q01",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "A-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G20",
            "Cut": {
              "Length": 606.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 4,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-A-S1-G20-R02-Q02",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "A-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G20",
            "Cut": {
              "Length": 606.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 5,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-B-S1-G20-R03-Q01",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "B-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G20",
            "Cut": {
              "Length": 606.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 6,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-B-S1-G20-R03-Q02",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "B-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G20",
            "Cut": {
              "Length": 606.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          }
        ]
      },
      {
        "DXF_Name": "SL-LHB8004-20T",
        "BarNumber": 2,
        "MaxY": 45.0,
        "MaxZ": 83.1,
        "Length": 4800.0,
        "BarName": "G21 - 4760.05.00.4880",
        "BarColor": "/",
        "BarLeftLength": 1776.4,
        "BarType": 2,
        "BarCad": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_182c74ad-02f4-4ba2-9de1-8171424f9168.png",
        "BarId": 135,
        "BarCad_file": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_22bbbd92-13c6-4baf-ab21-b5d1051b161c.dxf",
        "SortingCode": "G21",
        "Machining": {
          "Faces": []
        },
        "profile_type": null,
        "profile_type_sort": 1,
        "Piece": [
          {
            "PieceNumber": 1,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600451 A-A-S2-G21-R01-Q01",
            "Customer": "JOB 2600451",
            "Cc_code": "2600451",
            "Buyer": "2600451 A",
            "BuyAddress": "A-S2",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600451 A",
            "GroupCode": "G21",
            "Cut": {
              "Length": 1101.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 2,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-A-S1-G21-R02-Q01",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "A-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G21",
            "Cut": {
              "Length": 847.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 3,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-B-S1-G21-R03-Q01",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "B-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G21",
            "Cut": {
              "Length": 847.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          }
        ]
      },
      {
        "DXF_Name": "SL-LHB8004-20T",
        "BarNumber": 3,
        "MaxY": 45.0,
        "MaxZ": 83.1,
        "Length": 4800.0,
        "BarName": "G22 - 4762.05.00.4880",
        "BarColor": "/",
        "BarLeftLength": 1776.4,
        "BarType": 2,
        "BarCad": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_182c74ad-02f4-4ba2-9de1-8171424f9168.png",
        "BarId": 136,
        "BarCad_file": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_22bbbd92-13c6-4baf-ab21-b5d1051b161c.dxf",
        "SortingCode": "G22",
        "Machining": {
          "Faces": []
        },
        "profile_type": null,
        "profile_type_sort": 1,
        "Piece": [
          {
            "PieceNumber": 1,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600451 A-A-S2-G22-R01-Q01",
            "Customer": "JOB 2600451",
            "Cc_code": "2600451",
            "Buyer": "2600451 A",
            "BuyAddress": "A-S2",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600451 A",
            "GroupCode": "G22",
            "Cut": {
              "Length": 1101.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 2,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-A-S1-G22-R02-Q01",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "A-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G22",
            "Cut": {
              "Length": 847.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 3,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-B-S1-G22-R03-Q01",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "B-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G22",
            "Cut": {
              "Length": 847.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          }
        ]
      },
      {
        "DXF_Name": "SL-LHB8004-20T",
        "BarNumber": 4,
        "MaxY": 9.0,
        "MaxZ": 83.1,
        "Length": 4800.0,
        "BarName": "G23 - 5956.05.00.4880",
        "BarColor": "/",
        "BarLeftLength": 2077.6,
        "BarType": 2,
        "BarCad": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_182c74ad-02f4-4ba2-9de1-8171424f9168.png",
        "BarId": 137,
        "BarCad_file": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_22bbbd92-13c6-4baf-ab21-b5d1051b161c.dxf",
        "SortingCode": "G23",
        "Machining": {
          "Faces": []
        },
        "profile_type": null,
        "profile_type_sort": 1,
        "Piece": [
          {
            "PieceNumber": 1,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-A-S1-G23-R01-Q01",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "A-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G23",
            "Cut": {
              "Length": 1285.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 2,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-A-S1-G23-R01-Q02",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "A-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G23",
            "Cut": {
              "Length": 1285.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          }
        ]
      },
      {
        "DXF_Name": "SL-LHB8004-20T",
        "BarNumber": 5,
        "MaxY": 9.0,
        "MaxZ": 83.1,
        "Length": 4800.0,
        "BarName": "G24 - 5956.05.00.4880",
        "BarColor": "/",
        "BarLeftLength": 2077.6,
        "BarType": 2,
        "BarCad": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_182c74ad-02f4-4ba2-9de1-8171424f9168.png",
        "BarId": 138,
        "BarCad_file": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_22bbbd92-13c6-4baf-ab21-b5d1051b161c.dxf",
        "SortingCode": "G24",
        "Machining": {
          "Faces": []
        },
        "profile_type": null,
        "profile_type_sort": 1,
        "Piece": [
          {
            "PieceNumber": 1,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-A-S1-G24-R01-Q01",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "A-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G24",
            "Cut": {
              "Length": 1285.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 2,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-A-S1-G24-R01-Q02",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "A-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G24",
            "Cut": {
              "Length": 1285.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          }
        ]
      },
      {
        "DXF_Name": "SL-LHB8004-20T",
        "BarNumber": 6,
        "MaxY": 9.0,
        "MaxZ": 83.1,
        "Length": 4800.0,
        "BarName": "G25 - 5956.05.00.4880",
        "BarColor": "/",
        "BarLeftLength": 2077.6,
        "BarType": 2,
        "BarCad": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_182c74ad-02f4-4ba2-9de1-8171424f9168.png",
        "BarId": 139,
        "BarCad_file": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_22bbbd92-13c6-4baf-ab21-b5d1051b161c.dxf",
        "SortingCode": "G25",
        "Machining": {
          "Faces": []
        },
        "profile_type": null,
        "profile_type_sort": 1,
        "Piece": [
          {
            "PieceNumber": 1,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-B-S1-G25-R01-Q01",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "B-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G25",
            "Cut": {
              "Length": 1285.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 2,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-B-S1-G25-R01-Q02",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "B-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G25",
            "Cut": {
              "Length": 1285.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          }
        ]
      },
      {
        "DXF_Name": "SL-LHB8004-20T",
        "BarNumber": 7,
        "MaxY": 9.0,
        "MaxZ": 83.1,
        "Length": 4800.0,
        "BarName": "G26 - 5956.05.00.4880",
        "BarColor": "/",
        "BarLeftLength": 2077.6,
        "BarType": 2,
        "BarCad": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_182c74ad-02f4-4ba2-9de1-8171424f9168.png",
        "BarId": 140,
        "BarCad_file": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_22bbbd92-13c6-4baf-ab21-b5d1051b161c.dxf",
        "SortingCode": "G26",
        "Machining": {
          "Faces": []
        },
        "profile_type": null,
        "profile_type_sort": 1,
        "Piece": [
          {
            "PieceNumber": 1,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-B-S1-G26-R01-Q01",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "B-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G26",
            "Cut": {
              "Length": 1285.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 2,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-B-S1-G26-R01-Q02",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "B-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G26",
            "Cut": {
              "Length": 1285.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          }
        ]
      },
      {
        "DXF_Name": "SL-LHB8004-20T",
        "BarNumber": 8,
        "MaxY": 9.0,
        "MaxZ": 83.1,
        "Length": 4800.0,
        "BarName": "G27 - 5956.05.00.4880",
        "BarColor": "/",
        "BarLeftLength": 575.2,
        "BarType": 2,
        "BarCad": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_182c74ad-02f4-4ba2-9de1-8171424f9168.png",
        "BarId": 141,
        "BarCad_file": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_22bbbd92-13c6-4baf-ab21-b5d1051b161c.dxf",
        "SortingCode": "G27",
        "Machining": {
          "Faces": []
        },
        "profile_type": null,
        "profile_type_sort": 1,
        "Piece": [
          {
            "PieceNumber": 1,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-A-S1-G27-R01-Q01",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "A-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G27",
            "Cut": {
              "Length": 980.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 2,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-A-S1-G27-R01-Q02",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "A-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G27",
            "Cut": {
              "Length": 980.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 3,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-A-S1-G27-R02-Q01",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "A-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G27",
            "Cut": {
              "Length": 980.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 4,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-A-S1-G27-R02-Q02",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "A-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G27",
            "Cut": {
              "Length": 980.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          }
        ]
      },
      {
        "DXF_Name": "SL-LHB8004-20T",
        "BarNumber": 9,
        "MaxY": 9.0,
        "MaxZ": 83.1,
        "Length": 4800.0,
        "BarName": "G28 - 5956.05.00.4880",
        "BarColor": "/",
        "BarLeftLength": 575.2,
        "BarType": 2,
        "BarCad": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_182c74ad-02f4-4ba2-9de1-8171424f9168.png",
        "BarId": 142,
        "BarCad_file": "http://wincc.oss-cn-qingdao.aliyuncs.com/Wincc_dandongchuangyanjian/material/profile/image/barCad_22bbbd92-13c6-4baf-ab21-b5d1051b161c.dxf",
        "SortingCode": "G28",
        "Machining": {
          "Faces": []
        },
        "profile_type": null,
        "profile_type_sort": 1,
        "Piece": [
          {
            "PieceNumber": 1,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-B-S1-G28-R01-Q01",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "B-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G28",
            "Cut": {
              "Length": 980.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 2,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-B-S1-G28-R01-Q02",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "B-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G28",
            "Cut": {
              "Length": 980.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 3,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-B-S1-G28-R02-Q01",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "B-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G28",
            "Cut": {
              "Length": 980.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          },
          {
            "PieceNumber": 4,
            "Num": 1,
            "Over_status": 0,
            "BarCode": "2600452 A-B-S1-G28-R02-Q02",
            "Customer": "JOB 2600452",
            "Cc_code": "2600452",
            "Buyer": "2600452 A",
            "BuyAddress": "B-S1",
            "CtrsX": "0.0",
            "CtrsYp": "0.0",
            "CtrsYm": "0.0",
            "Mirror": "0.0",
            "Extra_Pie": null,
            "OrderCode": "2600452 A",
            "GroupCode": "G28",
            "Cut": {
              "Length": 980.0,
              "sxB": 45.0,
              "dxB": 45.0,
              "sxC": 90,
              "dxC": 90
            },
            "Work": [],
            "Machining": []
          }
        ]
      }
    ]
  },
  "meta": null
}
